### ISSUE TITLE
GraphViz Dependency Broken

### ISSUE THREAD

**Issue by deweller** [Metabor/Statemachine#10]
When I try to create a graph, I get this error:

```
Call to undefined method Fhaculty\Graph\Vertex::setLayout()' in metabor/statemachine/src/Metabor/Statemachine/Graph/GraphBuilder.php:124
```

**Comment by Metabor** [comment]
They changed the interface.
Either use:
"clue/graph": "0.7"
in your composer.json to switch back to the old clue/graph library.
or switch to the master
"metabor/statemachine": "dev-master"
where this problem should be solved.
Version 1.2 will be available in the beginning of march (after testing), that hasn't this issue.

Would be nice if you write if this helped you and what workaround you used,

**Comment by deweller** [comment]
I upgraded to `metabor/statemachine: dev-master` and that fixed the issue.  Thanks!

**Comment by Metabor** [comment]
Will write to you when release 1.2 is out, so that you can switch on a stable version again.

**Comment by Metabor** [comment]
Next release (version 1.1.1) is now out right now, that hasn't this issue anymore. So you can switch back to stable version.

**Comment by deweller** [comment]
Super.  thanks.
