### ISSUE TITLE
BC break introduced in 1.2

### ISSUE THREAD

**Issue by keradus** [Metabor/Statemachine#21]
Hi

v1.1.8:
https://github.com/Metabor/Statemachine/blob/v1.1.8/src/Metabor/Statemachine/Statemachine.php#L237
```php
public function checkTransitions()
```

v1.2.0:
https://github.com/Metabor/Statemachine/blob/v1.2.0/src/Metabor/Statemachine/Statemachine.php#L238
```php
public function checkTransitions(\ArrayAccess $context = null)
```

Adding new parameter to a method is a BC breaker, therefore should not be released with MINOR but with MAJOR version bump - 2.0.
Now, when my class extends `Statemachine` class from this library, it works on ^1.1 and crash on ^1.2, because of interface change and not matching method prototype.

Please revert the BC breaker or release it with respect to semver.

At the same time, same BC breaker at this library between 1.1 and 1.2:
https://github.com/Metabor/MetaborStd/blob/v1.1.4/src/MetaborStd/Statemachine/StatemachineInterface.php

**Comment by Metabor** [comment]
Sorry for inconvenience.
Will try to solve this by moving version to 2.0 in the next days.
As long as this is not done, please add "!=1.2.0" to your project.

**Comment by keradus** [comment]
Thanks for fast answer.

even after releasing 2.0 the 1.2.1 will still be broken. could you release 1.2.2 with a fix for that on 1.2 line ? (removing the parameter)

**Comment by Metabor** [comment]
I will remove the Tags 1.2.0 and 1.2.1 after I tagged it new. Hope this will solve it (but also need to take care that this did not brake two other projects)

**Comment by Metabor** [comment]
I moved the changes on checkTransition to Version 2.0 to cleaned up Version Tags 1.2.
Looks good for me now:
https://packagist.org/packages/metabor/metabor-std
https://packagist.org/packages/metabor/statemachine
Please check and give feedback if this fixed your problem with the overwritten Statemachine class.

**Comment by keradus** [comment]
Thank you. That solves the issue (could be funny for guys who already updated to 1.2...)

Maybe https://github.com/Metabor/Statemachine/blob/master/UPGRADE.md could be updated as well ?

**Comment by Metabor** [comment]
Done
